// iOS splash links — the branded launch image for the installed
// home-screen app. Safari shows a plain white flash between tapping
// the icon and the first paint; `apple-touch-startup-image` lets us
// own that moment with the Vanishing Ink seated on paper instead.
//
// The PNGs are generated by `bun scripts/gen-splash.ts` (see that
// file for the composition recipe) into public/splash/, one per
// iPhone/iPad resolution, named by real pixel size (css × dpr).
// The device table below mirrors DEVICES in the generator — keep
// the two in sync.
//
// Media queries use the standard Apple formula: exact css
// device-width + device-height + -webkit-device-pixel-ratio. iOS
// reports portrait dimensions regardless of orientation, so no
// orientation qualifier is needed — the simplest form that matches
// every device exactly once. Unmatched devices (future screens,
// Android) simply fall back to the paper background-color the web
// app already paints, which is the same colour as these splashes.
//
// This is a server component: React 19 hoists <link> elements into
// <head> wherever they are rendered, no next/head needed.

/** [cssW, cssH, dpr] — iPhone/iPad launch resolutions, mirroring
 *  DEVICES in scripts/gen-splash.ts. */
const DEVICES: ReadonlyArray<readonly [cssW: number, cssH: number, dpr: number]> = [
  [320, 568, 2], // iPhone SE (1st gen)
  [375, 667, 2], // iPhone SE (2nd/3rd), 6/7/8
  [375, 812, 3], // iPhone X/XS/11 Pro/12 mini
  [390, 844, 3], // iPhone 12/13/14
  [393, 852, 3], // iPhone 14 Pro/15
  [414, 736, 3], // iPhone 6/7/8 Plus
  [414, 896, 2], // iPhone XR/11
  [414, 896, 3], // iPhone XS Max/11 Pro Max
  [428, 926, 3], // iPhone 12/13/14 Plus, Pro Max
  [430, 932, 3], // iPhone 14/15/16 Pro Max
  [440, 956, 3], // iPhone 16 Pro
  [768, 1024, 2], // iPad Air/mini/9.7-10.2
  [1024, 1366, 2], // iPad Pro 12.9
];

export function AppleSplashLinks() {
  return (
    <>
      {DEVICES.map(([cssW, cssH, dpr]) => (
        <link
          key={`${cssW}x${cssH}@${dpr}`}
          rel="apple-touch-startup-image"
          media={`(device-width: ${cssW}px) and (device-height: ${cssH}px) and (-webkit-device-pixel-ratio: ${dpr})`}
          href={`/splash/splash-${cssW * dpr}x${cssH * dpr}.png`}
        />
      ))}
    </>
  );
}
